# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CarWash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarWash
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
  target 'CarWashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarWashUITests' do
    # Pods for testing
  end

end
